// Scheduled jobs for doitforme.
//
// A separate Worker on purpose. The main app is generated by
// @opennextjs/cloudflare, which rewrites .open-next/worker.js on every build —
// adding a `scheduled` handler there means either editing generated output or
// wrapping an entry whose named Durable Object exports change between adapter
// versions. This Worker just makes authenticated HTTP calls to cron routes that
// already exist and already verify CRON_SECRET, so nothing about it can be
// broken by a rebuild of the app.
//
// WHY THE SCHEDULES CHANGED. On Vercel Hobby every cron was capped at once per
// day and was only hour-accurate. auto-release is the one that hurt: a worker
// delivers, the poster has 24h to review, and the release only happens the next
// time the job runs — so a delivery landing just after the daily run waited
// closer to 48h for money the UI had already promised in 24. Cloudflare Cron
// Triggers have no such limit on any plan, so auto-release now runs every 15
// minutes and the 24h in the product copy is finally the truth.
//
// The other two keep their original UTC times so their behaviour is unchanged.

export interface Env {
  /** Origin of the deployed app, no trailing slash. e.g. https://doitforme.in */
  APP_ORIGIN: string;
  /** Must match the CRON_SECRET the app checks. Set with `wrangler secret put`. */
  CRON_SECRET: string;
}

/** cron expression -> the route it should call. Keep in sync with wrangler.jsonc. */
const SCHEDULE: Record<string, string> = {
  "*/15 * * * *": "/api/cron/auto-release",
  "30 7 * * *": "/api/cron/nudge-posters",
  "0 9 * * *": "/api/cron/process-payouts",
};

async function runJob(env: Env, path: string): Promise<void> {
  const url = `${env.APP_ORIGIN}${path}`;
  const started = Date.now();

  try {
    const res = await fetch(url, {
      method: "GET",
      headers: {
        "x-cron-secret": env.CRON_SECRET,
        "user-agent": "doitforme-cron/1.0",
      },
    });

    const body = await res.text();
    const ms = Date.now() - started;

    if (!res.ok) {
      // Logged, not thrown: a failing job should not retry in a tight loop, and
      // the next tick is at most 15 minutes away.
      console.error(`[cron] ${path} -> ${res.status} in ${ms}ms :: ${body.slice(0, 300)}`);
      return;
    }
    console.log(`[cron] ${path} -> ${res.status} in ${ms}ms :: ${body.slice(0, 300)}`);
  } catch (err) {
    console.error(`[cron] ${path} threw after ${Date.now() - started}ms:`, err);
  }
}

export default {
  async scheduled(event: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    const path = SCHEDULE[event.cron];
    if (!path) {
      console.error(`[cron] no route mapped for schedule "${event.cron}"`);
      return;
    }
    ctx.waitUntil(runJob(env, path));
  },

  // Manual trigger, so a job can be run on demand without waiting for its slot.
  // Requires the same secret the app does, so it is no weaker than the endpoint
  // it calls. Anything else 404s rather than describing the surface.
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname !== "/__run") return new Response("Not found", { status: 404 });

    if (request.headers.get("x-cron-secret") !== env.CRON_SECRET) {
      return new Response("Unauthorized", { status: 401 });
    }

    const job = url.searchParams.get("job");
    const path = Object.values(SCHEDULE).find((p) => p.endsWith(`/${job}`));
    if (!path) {
      return new Response(
        `Unknown job. Try one of: ${Object.values(SCHEDULE)
          .map((p) => p.split("/").pop())
          .join(", ")}`,
        { status: 400 }
      );
    }

    await runJob(env, path);
    return new Response(`ran ${path}\n`);
  },
};
