-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gig_id uuid,
  worker_id uuid,
  pitch text,
  status text DEFAULT 'applied'::text,
  created_at timestamp without time zone DEFAULT now(),
  finish_by timestamp with time zone,
  negotiated_price numeric CHECK (negotiated_price >= 0::numeric),
  payment_preference text DEFAULT 'DIRECT'::text CHECK (payment_preference = ANY (ARRAY['ESCROW'::text, 'DIRECT'::text])),
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT applications_gig_id_fkey FOREIGN KEY (gig_id) REFERENCES public.gigs(id),
  CONSTRAINT applications_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_blocked_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id uuid,
  sender_id uuid,
  message text,
  reason text,
  blocked_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_blocked_logs_pkey PRIMARY KEY (id),
  CONSTRAINT chat_blocked_logs_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  contact_email text,
  website text,
  company_type text CHECK (company_type = ANY (ARRAY['startup'::text, 'agency'::text, 'enterprise'::text, 'ngo'::text, 'other'::text])),
  free_credits integer DEFAULT 3,
  logo_url text,
  description text,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid,
  file_url text,
  notes text,
  status text DEFAULT 'submitted'::text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT deliveries_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.disputes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gig_id uuid,
  raised_by uuid,
  reason text NOT NULL,
  status text DEFAULT 'OPEN'::text CHECK (status = ANY (ARRAY['OPEN'::text, 'RESOLVED'::text, 'REJECTED'::text])),
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT disputes_pkey PRIMARY KEY (id),
  CONSTRAINT disputes_gig_id_fkey FOREIGN KEY (gig_id) REFERENCES public.gigs(id),
  CONSTRAINT disputes_raised_by_fkey FOREIGN KEY (raised_by) REFERENCES public.users(id)
);
CREATE TABLE public.escrow (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gig_id uuid NOT NULL UNIQUE,
  poster_id uuid NOT NULL,
  worker_id uuid,
  original_amount numeric NOT NULL,
  platform_fee numeric NOT NULL,
  gateway_fee numeric NOT NULL,
  amount_held numeric NOT NULL,
  release_date timestamp without time zone NOT NULL,
  status text DEFAULT 'HELD'::text,
  created_at timestamp without time zone DEFAULT now(),
  amount numeric,
  released_at timestamp with time zone,
  refunded_at timestamp with time zone,
  escrow_category text DEFAULT 'GIG'::text CHECK (escrow_category = ANY (ARRAY['GIG'::text, 'RENTAL_DEPOSIT'::text, 'MARKETPLACE'::text])),
  handshake_code text,
  handshake_verified_at timestamp with time zone,
  CONSTRAINT escrow_pkey PRIMARY KEY (id),
  CONSTRAINT escrow_gig_id_fkey FOREIGN KEY (gig_id) REFERENCES public.gigs(id),
  CONSTRAINT escrow_poster_id_fkey FOREIGN KEY (poster_id) REFERENCES public.users(id),
  CONSTRAINT escrow_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.users(id)
);
CREATE TABLE public.escrow_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gig_id uuid,
  worker_id uuid,
  poster_id uuid,
  amount numeric,
  platform_fee numeric DEFAULT 0,
  type text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT escrow_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gigs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poster_id uuid,
  title text,
  description text,
  price integer CHECK (price >= 0),
  is_physical boolean DEFAULT false,
  location text,
  status text DEFAULT 'draft'::text,
  escrow_order_id text,
  deadline timestamp with time zone,
  created_at timestamp without time zone DEFAULT now(),
  escrow_status text DEFAULT 'NONE'::text,
  assigned_worker_id uuid,
  delivery_files ARRAY,
  delivered_at timestamp with time zone,
  escrow_amount numeric,
  escrow_locked_at timestamp with time zone,
  payment_status text DEFAULT 'PENDING'::text,
  images ARRAY DEFAULT '{}'::text[],
  delivery_link text,
  payment_gateway text,
  gateway_order_id text,
  payment_session_id text,
  currency text DEFAULT 'INR'::text,
  dispute_reason text,
  auto_release_at timestamp with time zone,
  gateway_fee numeric DEFAULT 0,
  platform_fee numeric DEFAULT 0,
  net_worker_pay numeric DEFAULT 0,
  listing_type text DEFAULT 'HUSTLE'::text CHECK (listing_type = ANY (ARRAY['HUSTLE'::text, 'MARKET'::text, 'COMPANY_TASK'::text])),
  market_type text CHECK (market_type IS NULL OR (market_type = ANY (ARRAY['SELL'::text, 'RENT'::text, 'FREE'::text, 'BUY_REQUEST'::text, 'REQUEST'::text]))),
  item_condition text CHECK (item_condition = ANY (ARRAY['NEW'::text, 'LIKE_NEW'::text, 'GOOD'::text, 'FAIR'::text])),
  security_deposit numeric DEFAULT 0,
  github_link text,
  is_highlighted boolean DEFAULT false,
  highlight_expires_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  category text,
  handshake_code text,
  max_workers integer DEFAULT 1,
  trust_based boolean DEFAULT false,
  company_id uuid,
  CONSTRAINT gigs_pkey PRIMARY KEY (id),
  CONSTRAINT gigs_poster_id_fkey FOREIGN KEY (poster_id) REFERENCES public.users(id),
  CONSTRAINT gigs_assigned_worker_id_fkey FOREIGN KEY (assigned_worker_id) REFERENCES public.users(id),
  CONSTRAINT gigs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gig_id uuid,
  sender_id uuid,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  is_pre_agreement boolean DEFAULT true,
  receiver_id uuid,
  flagged_for_review boolean DEFAULT false,
  message_type text DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'offer'::text, 'system'::text])),
  offer_amount numeric,
  offer_status text DEFAULT 'pending'::text CHECK (offer_status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_gig_id_fkey FOREIGN KEY (gig_id) REFERENCES public.gigs(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  content text NOT NULL,
  link text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payout_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  details jsonb NOT NULL,
  is_primary boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT payout_methods_pkey PRIMARY KEY (id),
  CONSTRAINT payout_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payout_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid NOT NULL,
  gig_id uuid,
  amount numeric NOT NULL,
  upi_id text,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'COMPLETED'::text, 'FAILED'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  CONSTRAINT payout_queue_pkey PRIMARY KEY (id),
  CONSTRAINT payout_queue_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.users(id),
  CONSTRAINT payout_queue_gig_id_fkey FOREIGN KEY (gig_id) REFERENCES public.gigs(id)
);
CREATE TABLE public.points_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  amount integer NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['EARN'::text, 'SPEND'::text, 'EXPIRED'::text])),
  reason text NOT NULL,
  reference_id text,
  expires_at timestamp with time zone,
  redeemed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT points_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT points_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rater_id uuid,
  rated_id uuid,
  gig_id uuid,
  score integer CHECK (score >= 1 AND score <= 5),
  created_at timestamp without time zone DEFAULT now(),
  review text,
  CONSTRAINT ratings_pkey PRIMARY KEY (id),
  CONSTRAINT ratings_gig_id_fkey FOREIGN KEY (gig_id) REFERENCES public.gigs(id),
  CONSTRAINT ratings_rated_id_fkey FOREIGN KEY (rated_id) REFERENCES public.users(id),
  CONSTRAINT ratings_rater_id_fkey FOREIGN KEY (rater_id) REFERENCES public.users(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid,
  referred_id uuid,
  status text DEFAULT 'SIGNED_UP'::text CHECK (status = ANY (ARRAY['SIGNED_UP'::text, 'FIRST_GIG_DONE'::text])),
  signup_reward_paid boolean DEFAULT false,
  gig_bonus_paid boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.users(id),
  CONSTRAINT referrals_referred_id_fkey FOREIGN KEY (referred_id) REFERENCES public.users(id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reporter_id uuid NOT NULL,
  target_id uuid NOT NULL,
  target_type text NOT NULL CHECK (target_type = ANY (ARRAY['gig'::text, 'user'::text])),
  reason text NOT NULL,
  details text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'reviewed'::text, 'resolved'::text, 'dismissed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES auth.users(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gig_id uuid,
  amount integer,
  type text,
  status text DEFAULT 'pending'::text,
  provider_data jsonb,
  created_at timestamp without time zone DEFAULT now(),
  gateway_payment_id text,
  user_id uuid,
  gateway text DEFAULT 'CASHFREE'::text,
  gateway_order_id text,
  split_id text,
  category text DEFAULT 'PAYMENT'::text,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_gig_id_fkey FOREIGN KEY (gig_id) REFERENCES public.gigs(id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text UNIQUE,
  name text,
  phone numeric CHECK (phone > 100000000::numeric),
  id_card_url text,
  kyc_verified boolean DEFAULT false,
  rating numeric,
  rating_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  role text DEFAULT 'user'::text,
  jobs_completed integer DEFAULT 0,
  country text DEFAULT 'INDIA'::text,
  college text,
  updated_at timestamp with time zone DEFAULT now(),
  upi_id text,
  total_earned numeric DEFAULT 0,
  avatar_url text,
  referral_code text UNIQUE,
  referred_by text,
  points_balance integer DEFAULT 0,
  preferences ARRAY DEFAULT '{}'::text[],
  profile_last_edited_at timestamp with time zone,
  telegram_chat_id text UNIQUE,
  skills ARRAY DEFAULT '{}'::text[],
  portfolio_links ARRAY DEFAULT '{}'::text[],
  experience text,
  resume_url text,
  is_verified_company boolean DEFAULT false,
  username text UNIQUE,
  display_name text,
  year_of_study integer,
  branch text,
  bio text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vasooli_bounties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creditor_id uuid NOT NULL,
  target_name text NOT NULL,
  target_phone numeric NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  reason text,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'ACTIVE'::text, 'RESOLVED'::text, 'OPTED_OUT'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vasooli_bounties_pkey PRIMARY KEY (id),
  CONSTRAINT vasooli_bounties_creditor_id_fkey FOREIGN KEY (creditor_id) REFERENCES public.users(id)
);
CREATE TABLE public.wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  balance numeric DEFAULT 0,
  frozen numeric DEFAULT 0,
  total_earned numeric DEFAULT 0,
  total_withdrawn numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wallets_pkey PRIMARY KEY (id),
  CONSTRAINT wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);